// Generated from Book4.xlsx (sheet: Employee Database)

export const workers = [
    {
        name: "Ding Chun Rong",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "China",
        race: "Chinese",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: 2500,
        minimumWorkingHours: 260,
        hourlyRate: 8,
        restDayRate: 88.76,
        paymentMethod: "PayNow",
        payNowPhone: "65 8608 6736",
        bankAccountNumber: null,
    },
    {
        name: "Nguyen Thi Thao",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Vietnam",
        race: "Vietnamese",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: 1700,
        minimumWorkingHours: 260,
        hourlyRate: 7,
        restDayRate: 60.36,
        paymentMethod: "PayNow",
        payNowPhone: "65 8173 6958",
        bankAccountNumber: null,
    },
    {
        name: "Nyan Htoo",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Myanmar",
        race: "Burmese",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: 1800,
        minimumWorkingHours: 250,
        hourlyRate: 8,
        restDayRate: 63.91,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Sunthar",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: 1300,
        minimumWorkingHours: 250,
        hourlyRate: 6,
        restDayRate: null,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Kaalidas Rajendran",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: 1700,
        minimumWorkingHours: 260,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: "PayNow",
        payNowPhone: "65 8421 7120",
        bankAccountNumber: null,
    },
    {
        name: "Lochme",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: 1300,
        minimumWorkingHours: 260,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Sangeetha",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: 1300,
        minimumWorkingHours: 190,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: "Bank Transfer",
        payNowPhone: null,
        bankAccountNumber: "452-10686-8",
    },
    {
        name: "Anbarasan A/L Nagiendran",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: null,
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: 1300,
        minimumWorkingHours: 190,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Sar Dar",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Bangladesh",
        race: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 8,
        restDayRate: null,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Jaya",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: null,
        race: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 6,
        restDayRate: null,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Sein Sein",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: null,
        race: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 7,
        restDayRate: null,
        paymentMethod: "Bank Transfer",
        payNowPhone: null,
        bankAccountNumber: "426-26745-4",
    },
    {
        name: "Cindy",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: "Chinese",
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 7,
        restDayRate: null,
        paymentMethod: "PayNow",
        payNowPhone: "65 8038 3538",
        bankAccountNumber: null,
    },
    {
        name: "Aunt Ong",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: "Chinese",
        employmentType: "Part Time",
        employmentArrangement: "Local Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 7,
        restDayRate: null,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Kuldeep Kaur",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: null,
        race: null,
        employmentType: "Part Time",
        employmentArrangement: "Local Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 6,
        restDayRate: null,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Saraswathy",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: "Indian",
        employmentType: "Part Time",
        employmentArrangement: "Local Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 6,
        restDayRate: null,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Sunita",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: null,
        race: null,
        employmentType: "Part Time",
        employmentArrangement: "Local Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 6,
        restDayRate: null,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Ashaduzzaman",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: null,
        race: null,
        employmentType: "Part Time",
        employmentArrangement: "Local Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 6,
        restDayRate: null,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Tan Fook Chye",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Part Time",
        employmentArrangement: "Local Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: 8,
        restDayRate: null,
        paymentMethod: "Bank Transfer",
        payNowPhone: null,
        bankAccountNumber: "018-00229-9",
    },
    {
        name: "Ng Lye Kiat",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 231,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Ong Siew Lay",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 231,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Kwek Joo Soon",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 175,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Chen Wai Tak",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 308,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Chue Chee Wye",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 308,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Yeo Robert",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 175,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Ong Siew Tuan",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 434,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Ho Poh Lian",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 231,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Ang Kee Soon",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 308,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Toh Chiew Huah",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 308,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Yeo Kim Hock",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 175,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Tan Kim Moi",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 175,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Tan Fook Chye",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 175,
        monthlyPay: 1400,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
    {
        name: "Alvis Ong Thai Ying",
        email: null,
        phone: null,
        status: "Active",
        countryOfOrigin: "Singapore",
        race: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: null,
        monthlyPay: null,
        minimumWorkingHours: null,
        hourlyRate: null,
        restDayRate: null,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
    },
] as const;
