export const workers = [
    {
        name: "Ding Chun Rong",
        status: "Active",
        countryOfOrigin: "China",
        race: "Chinese",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 4000,
        hourlyRate: 0,
        restDayRate: 0,
        paymentMethod: "PayNow",
        payNowPhone: "6586086736",
    },
    {
        name: "Nguyen Thi Thao",
        status: "Active",
        countryOfOrigin: "Vietnam",
        race: "Vietnamese",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 1800,
        minimumWorkingHours: 260,
        hourlyRate: 7,
        restDayRate: 63.91,
        paymentMethod: "PayNow",
        payNowPhone: "6581736958",
    },
    {
        name: "Nyan Htoo",
        status: "Active",
        countryOfOrigin: "Myanmar",
        race: "Burmese",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 1900,
        minimumWorkingHours: 260,
        hourlyRate: 8,
        restDayRate: 63.91,
        paymentMethod: "Cash",
    },
    {
        name: "Wang Yan Qing",
        status: "Active",
        countryOfOrigin: "China",
        race: "Chinese",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 1700,
        minimumWorkingHours: 260,
        hourlyRate: 7,
        restDayRate: 60.36,
        paymentMethod: "Cash",
    },
    {
        name: "Wang Ming Yu",
        status: "Active",
        countryOfOrigin: "China",
        race: "Chinese",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 1600,
        minimumWorkingHours: 260,
        hourlyRate: 7,
        restDayRate: 56.8,
        paymentMethod: "Cash",
    },
    {
        name: "Pathmavathy",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: "Indian",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 1600,
        minimumWorkingHours: 260,
        hourlyRate: 7,
        restDayRate: 56.8,
        paymentMethod: "Cash",
    },
    {
        name: "Kishok",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: "Indian",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 1700,
        minimumWorkingHours: 260,
        hourlyRate: 7,
        restDayRate: 58.58,
        paymentMethod: "Cash",
    },
    {
        name: "Ashaduzzaman",
        status: "Active",
        countryOfOrigin: "India",
        race: "Indian",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        shiftPattern: "Night Shift",
        monthlyPay: 1400,
        minimumWorkingHours: 260,
        hourlyRate: 6,
        restDayRate: 49.7,
        paymentMethod: "Cash",
    },
    {
        name: "Monir",
        status: "Active",
        countryOfOrigin: "India",
        race: "Indian",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        shiftPattern: "Night Shift",
        monthlyPay: 1700,
        minimumWorkingHours: 260,
        hourlyRate: 7,
        restDayRate: 56.8,
        paymentMethod: "Cash",
    },
    {
        name: "Yogesh",
        status: "Active",
        countryOfOrigin: "India",
        race: "Indian",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        shiftPattern: "Night Shift",
        monthlyPay: 1400,
        minimumWorkingHours: 260,
        hourlyRate: 6,
        restDayRate: 49.7,
        paymentMethod: "Cash",
    },
    {
        name: "Tharman",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: "Indian",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 1300,
        minimumWorkingHours: 260,
        hourlyRate: 6,
        restDayRate: 46.15,
        paymentMethod: "Cash",
    },
    {
        name: "Ganesh",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: "Indian",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 1300,
        minimumWorkingHours: 260,
        hourlyRate: 6,
        restDayRate: 46.15,
        paymentMethod: "Cash",
    },
    {
        name: "Ahmmed",
        status: "Active",
        countryOfOrigin: "India",
        race: "Indian",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        monthlyPay: 3000,
        minimumWorkingHours: 260,
        hourlyRate: 10,
        restDayRate: 98.9,
        paymentMethod: "Cash",
    },
    {
        name: "Ong Siew Lay",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "KWEK JOO SOON",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "YEO ROBERT",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "ONG SIEW TUAN",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "HO POH LIAN",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1650,
        paymentMethod: "Cash",
    },
    {
        name: "TOH CHIEW HUAH",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 330,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "YEO KIM HOCK",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "TAN KIM MOI",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 330,
        monthlyPay: 1650,
        paymentMethod: "Cash",
    },
    {
        name: "TAN TIAN SOO",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "ALVIS ONG THAI YING",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        monthlyPay: 5000,
        paymentMethod: "Cash",
    },
    {
        name: "ONG CHONG WEE",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        monthlyPay: 5000,
        paymentMethod: "Cash",
    },
    {
        name: "SHEBE ONG LI YING",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "CHIAM BOON HWEE",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "ANG AH CHIA",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1650,
        paymentMethod: "Cash",
    },
    {
        name: "TAN GIOK",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "LIM GHEE HENG",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "ONG BENG KHENG",
        status: "Active",
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        cpf: 320,
        monthlyPay: 1600,
        paymentMethod: "Cash",
    },
    {
        name: "Shubam Soni",
        status: "Active",
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        hourlyRate: 6,
        paymentMethod: "Cash",
    },
    {
        name: "Lovepreet",
        status: "Active",
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        hourlyRate: 7,
        paymentMethod: "Cash",
    },
    {
        name: "Shashi",
        status: "Active",
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        hourlyRate: 6,
        paymentMethod: "Cash",
    },
    {
        name: "Ariful",
        status: "Active",
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        hourlyRate: 6,
        paymentMethod: "Cash",
    },
    {
        name: "Rudas",
        status: "Active",
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        hourlyRate: 6,
        paymentMethod: "Cash",
    },
    {
        name: "Ram",
        status: "Active",
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        hourlyRate: 6,
        paymentMethod: "Cash",
    },
    {
        name: "Nangilabror",
        status: "Active",
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        hourlyRate: 6,
        paymentMethod: "Cash",
    },
] as const;
