import type {
    workerTable,
    InsertWorker,
} from "@/db/tables/payroll/workerTable";

function isoDate(): Date {
    return new Date();
}

export const workers = [
    // ── Full-Time employees ──────────────────────────────────────────────────
    {
        name: "Ding Chun Rong",
        email: "",
        phone: "+6586086736",
        status: "Active",
        countryOfOrigin: "China",
        race: "Chinese",
        type: "Full Time",
        arrangement: "Foreign Worker",
        monthlyPay: 2500,
        workingHours: 40,
        hourlyPay: 12,
        restDayPay: 100,
        paymentMethod: "PayNow",
        payNowPhone: "+6586086736",
        bankAccountNumber: null,
    },
    {
        name: "Nguyen Thi Thao",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "Vietnam",
        race: null,
        monthlyPay: 1700,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Nyan Htoo",
        email: "",
        phone: "+6581736958",
        status: "Active",
        countryOfOrigin: "Myanmar",
        race: null,
        monthlyPay: 1800,
        paymentMethod: "PayNow",
        payNowPhone: "+6581736958",
        bankAccountNumber: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Sunthar",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: null,
        monthlyPay: 1300,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Kaalidas Rajendran",
        email: "",
        phone: "+6584217120",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: null,
        monthlyPay: 1700,
        paymentMethod: "PayNow",
        payNowPhone: "+6584217120",
        bankAccountNumber: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Lochme",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: null,
        monthlyPay: 1300,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Sangeetha",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: null,
        monthlyPay: 1300,
        paymentMethod: "Bank Transfer",
        payNowPhone: null,
        bankAccountNumber: "452-10686-8",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Anbarasan A/L Nagiendran",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: null,
        race: null,
        monthlyPay: 1300,
        paymentMethod: null,
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    // ── Part-Time employees ──────────────────────────────────────────────────
    {
        name: "Sar Dar",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "Bangladesh",
        race: null,
        hourlyPay: 8,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Jaya",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: null,
        race: null,
        hourlyPay: 6,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Sein Sein",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: null,
        race: null,
        hourlyPay: 7,
        paymentMethod: "Bank Transfer",
        payNowPhone: null,
        bankAccountNumber: "426-26745-4",
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Cindy",
        email: "",
        phone: "+6580383538",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: "Chinese",
        hourlyPay: 7,
        paymentMethod: "PayNow",
        payNowPhone: "+6580383538",
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Aunt Ong",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "Singapore",
        race: "Chinese",
        hourlyPay: 7,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Local Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Kuldeep Kaur",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: null,
        race: null,
        hourlyPay: 6,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Saraswathy",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: "Indian",
        hourlyPay: 6,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Sunita",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: null,
        race: null,
        hourlyPay: 6,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Ashaduzzaman",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: null,
        race: null,
        hourlyPay: 6,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Tan Fook Chye",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "Singapore",
        race: "Chinese",
        hourlyPay: 8,
        paymentMethod: "Bank Transfer",
        payNowPhone: null,
        bankAccountNumber: "018-00229-9",
        employmentType: "Part Time",
        employmentArrangement: "Local Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Ramesh Kumar",
        email: "ramesh.k@company.com",
        phone: "+6591234567",
        status: "Active",
        countryOfOrigin: "India",
        race: "Indian",
        monthlyPay: 2200,
        paymentMethod: "Bank Transfer",
        payNowPhone: null,
        bankAccountNumber: "123-45678-9",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Li Wei",
        email: "li.wei@company.com",
        phone: "+6598765432",
        status: "Active",
        countryOfOrigin: "China",
        race: "Chinese",
        monthlyPay: 2600,
        paymentMethod: "PayNow",
        payNowPhone: "+6598765432",
        bankAccountNumber: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Ahmad Hassan",
        email: "",
        phone: "+6591122334",
        status: "Active",
        countryOfOrigin: "Malaysia",
        race: "Malay",
        monthlyPay: 1900,
        paymentMethod: "PayNow",
        payNowPhone: "+6591122334",
        bankAccountNumber: null,
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Maria Santos",
        email: "maria.s@company.com",
        phone: "",
        status: "Active",
        countryOfOrigin: "Philippines",
        race: null,
        monthlyPay: 1500,
        paymentMethod: "Bank Transfer",
        payNowPhone: null,
        bankAccountNumber: "789-01234-5",
        employmentType: "Full Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "John Tan",
        email: "john.tan@company.com",
        phone: "+6595544332",
        status: "Active",
        countryOfOrigin: "Singapore",
        race: "Chinese",
        monthlyPay: 2800,
        paymentMethod: "PayNow",
        payNowPhone: "+6595544332",
        bankAccountNumber: null,
        employmentType: "Full Time",
        employmentArrangement: "Local Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Priya Devi",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "India",
        race: "Indian",
        hourlyPay: 7,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Muhammad Rizwan",
        email: "",
        phone: "+6596655443",
        status: "Active",
        countryOfOrigin: "Bangladesh",
        race: null,
        hourlyPay: 8,
        paymentMethod: "PayNow",
        payNowPhone: "+6596655443",
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Chen Mei Ling",
        email: "meiling.c@company.com",
        phone: "",
        status: "Active",
        countryOfOrigin: "Singapore",
        race: "Chinese",
        hourlyPay: 9,
        paymentMethod: "Bank Transfer",
        payNowPhone: null,
        bankAccountNumber: "555-66778-1",
        employmentType: "Part Time",
        employmentArrangement: "Local Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Rajesh Pillai",
        email: "",
        phone: "",
        status: "Active",
        countryOfOrigin: "Sri Lanka",
        race: null,
        hourlyPay: 7,
        paymentMethod: "Cash",
        payNowPhone: null,
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
    {
        name: "Siti Aminah",
        email: "siti.a@company.com",
        phone: "+6597788990",
        status: "Active",
        countryOfOrigin: "Indonesia",
        race: "Malay",
        hourlyPay: 8,
        paymentMethod: "PayNow",
        payNowPhone: "+6597788990",
        bankAccountNumber: null,
        employmentType: "Part Time",
        employmentArrangement: "Foreign Worker",
        createdAt: isoDate(),
        updatedAt: isoDate(),
    },
];
